# Play one, provision server in Amazon EC2
- hosts: localhost
  connection: local
  gather_facts: False
  vars_files:
    - vars/vars.yml
  tasks:
  - name: Download prerequisites script which will be run on Bicycle server on boot
    get_url:
      url: https://raw.githubusercontent.com/mglantz/bicycle/master/provisioning/prerequisites.sh
      dest: /tmp/prerequisites.sh

  - name: Ensure a security group with correct ingress/egress rules are in place
    ec2_group:
      name: "{{ ec2_security_group }}"
      description: Security Group for Bicycle server
      region: "{{ region }}"
      aws_access_key: "{{ec2_access_key}}"
      aws_secret_key: "{{ec2_secret_key}}"
      rules:
        - proto: tcp
          from_port: 22
          to_port: 22
          cidr_ip: 0.0.0.0/0
        - proto: tcp
          from_port: 80
          to_port: 80
          cidr_ip: 0.0.0.0/0
        - proto: tcp
          from_port: 443
          to_port: 443
          cidr_ip: 0.0.0.0/0
      rules_egress:
        - proto: all
          cidr_ip: 0.0.0.0/0

  - name: Provision Bicycle server
    ec2:
      aws_access_key: "{{ec2_access_key}}"
      aws_secret_key: "{{ec2_secret_key}}"
      key_name: redhat-roadshow
      region: "{{ region }}"
      group: "{{ ec2_security_group }}"
      instance_type: "{{ec2_instance_type}}"
      image: "{{ ami_id }}"
      user_data: "{{ lookup('file', '/tmp/prerequisites.sh') }}"
      wait: true
      exact_count: 1
      count_tag:
        identity: bicycle
      instance_tags:
        identity: bicycle
    register: bicycle

  - name: Debug
    debug: var=item
    with_items: bicycle.instances

  - name: Add Bicycle instance public IPs to host group
    add_host: hostname={{ item.public_ip }} groups=bicycle
    with_items: "{{ bicycle.tagged_instances }}"

  - name: Print IP address of Bicycle server
    debug:
      msg: "{{ groups['bicycle'] }}"

# Play two, install and configure Bicycle software
- hosts: bicycle
  gather_facts: False
  tasks:
  - name: Wait for the instances to boot by checking the ssh port
    wait_for:
      port=22
      delay=60
      timeout=300

  - name: Install Bicycle RPM prerequisites
    yum:
      name: "{{ packages }}"
    vars:
      packages:
      - httpd
      - httpd-tools
      - createrepo
      - yum-utils

  - name: Create www directory
    file:
      path: /var/www/html
      state: directory
      mode: 0755

