# Play to sync repositories from RHN
- hosts: all
  connection: local
  gather_facts: False

#  - name: Enable rhel-7-server repositories
#    rhsm_repository:
#      name: "{{ repo }}"
#      state: enabled

  - name: Ensure repo directory exists
    file:
      path: /var/www/html/repos
      state: directory
      recurse: yes
      setype: httpd_sys_content_t
      serole: object_r
      seuser: system_u


  - name: Run reposync for repository
    shell: reposync --gpgcheck -l --repoid="{{ repo }}" --download_path=/var/www/html/repos --downloadcomps --download-metadata

  - name: Create repository for rhel-7-server-rpms
    shell: createrepo -v /var/www/html/repos/{{ repo }}/ -g /var/www/html/repos/{{ repo }}/comps.xml
    
  - name: ensure selinux file contexts
    command: restorecon -R "/var/www/html/repos/{{ repo }}"
    
