- hosts: bicycle-servers
  vars:
    vdo_disk: sdb
    vdo_disk_name: vdo1
    vdo_logical_size: 200G
    repo_directory: /var/www/html/repos
    #  become: true

  tasks:

  - name: sync from tandem-master
    synchronize:
      src: /var/www/html/repos/
      dest: /var/www/html/repos
    delegate_to: "{{ tandem_master }}"
    when: tandem_master != ""
    register: repo_sync

  - name: get a list of repo files
    shell: find /var/www/html/repos -type f -name "*.repo" | xargs basename -a
    register: repos
    tags: get_repos
    when: tandem_master != "" and repo_sync.changed

#  - debug:
#      var: repos

  - name: update .repo files
    template:
      src: templates/repository-item.repo.j2
      dest: "/var/www/html/repos/{{ item }}"
    with_items:
      - "{{ repos.stdout_lines }}"
    when: tandem_master != "" and repo_sync.changed
    tags: repo
